//! GitLab secret patterns.

crate::declare_provider!(
    GitLabProvider,
    id: "gitlab",
    name: "GitLab",
    group: Group::Vcs,
    patterns: [
        crate::pattern! {
                id: "vcs/gitlab-pat",
                group: Group::Vcs,
                name: "GitLab Personal Access Token",
                description: "Grants API and Git access based on token scopes.",
                severity: Severity::Critical,
                regex: r"\b(glpat-[0-9a-zA-Z_-]{20})\b",
                keywords: &["glpat-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "vcs/gitlab-pat-routable",
                group: Group::Vcs,
                name: "GitLab Personal Access Token (Routable)",
                description: "Grants API and Git access with embedded routing for multi-cell deployments.",
                severity: Severity::Critical,
                regex: r"\b(glpat-[0-9a-zA-Z_-]{27,300}\.[0-9a-zA-Z_-]+)\b",
                keywords: &["glpat-"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "vcs/gitlab-pipeline-token",
                group: Group::Vcs,
                name: "GitLab Pipeline Trigger Token",
                description: "Can trigger CI/CD pipelines remotely.",
                severity: Severity::High,
                regex: r"\b(glptt-[0-9a-zA-Z_-]{20,64})\b",
                keywords: &["glptt-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "vcs/gitlab-runner-token",
                group: Group::Vcs,
                name: "GitLab Runner Registration Token",
                description: "Allows registering new CI/CD runners.",
                severity: Severity::High,
                regex: r"\b(glrt-[0-9a-zA-Z_-]{20,64})\b",
                keywords: &["glrt-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "vcs/gitlab-deploy-token",
                group: Group::Vcs,
                name: "GitLab Deploy Token",
                description: "Grants read-only access to repositories and registries.",
                severity: Severity::Medium,
                regex: r"\b(gldt-[0-9a-zA-Z_-]{20,64})\b",
                keywords: &["gldt-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "vcs/gitlab-agent-token",
                group: Group::Vcs,
                name: "GitLab Agent for Kubernetes Token",
                description: "Connects Kubernetes clusters to GitLab for deployments.",
                severity: Severity::Critical,
                regex: r"\b(glagent-[0-9a-zA-Z_-]{48,64})\b",
                keywords: &["glagent-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "vcs/gitlab-feed-token",
                group: Group::Vcs,
                name: "GitLab Feed Token",
                description: "Grants read access to RSS feeds of private resources.",
                severity: Severity::Medium,
                regex: r"\b(glft-[0-9a-zA-Z_-]{20,64})\b",
                keywords: &["glft-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "vcs/gitlab-incoming-email-token",
                group: Group::Vcs,
                name: "GitLab Incoming Email Token",
                description: "Allows creating issues and comments via email.",
                severity: Severity::Medium,
                regex: r"\b(glimt-[0-9a-zA-Z_-]{20,64})\b",
                keywords: &["glimt-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "vcs/gitlab-feature-flags-token",
                group: Group::Vcs,
                name: "GitLab Feature Flags Client Token",
                description: "Grants access to retrieve feature flag configurations.",
                severity: Severity::Medium,
                regex: r"\b(glffct-[0-9a-zA-Z_-]{20,64})\b",
                keywords: &["glffct-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "vcs/gitlab-scim-token",
                group: Group::Vcs,
                name: "GitLab SCIM Token",
                description: "Allows managing group membership via SCIM provisioning.",
                severity: Severity::High,
                regex: r"\b(glsoat-[0-9a-zA-Z_-]{20,64})\b",
                keywords: &["glsoat-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "vcs/gitlab-oauth-app-secret",
                group: Group::Vcs,
                name: "GitLab OAuth Application Secret",
                description: "Enables OAuth authentication flows for the application.",
                severity: Severity::High,
                regex: r"\b(gloas-[0-9a-fA-F]{64})\b",
                keywords: &["gloas-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "vcs/gitlab-legacy-runner-token",
                group: Group::Vcs,
                name: "GitLab Legacy Runner Token",
                description: "Allows registering CI/CD runners (deprecated, removal in GitLab 20.0).",
                severity: Severity::High,
                regex: r"\b(GR1348941[0-9a-zA-Z_-]{20})\b",
                keywords: &["GR1348941"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "vcs/gitlab-workspace-token",
                group: Group::Vcs,
                name: "GitLab Workspace Token",
                description: "Grants internal access for GitLab Workspaces communication.",
                severity: Severity::Medium,
                regex: r"\b(glwt-[0-9a-zA-Z_-]{20,64})\b",
                keywords: &["glwt-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
    ],
);
