//! OpenAI secret patterns.

crate::declare_provider!(
    OpenAiProvider,
    id: "openai",
    name: "OpenAI",
    group: Group::Ai,
    patterns: [
        crate::pattern! {
                id: "ai/openai-admin-key",
                group: Group::Ai,
                name: "OpenAI Admin API Key",
                description: "Grants administrative access to organisation.",
                severity: Severity::Critical,
                regex: r"\b(sk-admin-[a-zA-Z0-9_-]{20,})\b",
                keywords: &["sk-admin-"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "ai/openai-api-key",
                group: Group::Ai,
                name: "OpenAI Project API Key",
                description: "Grants access to OpenAI models with billing.",
                severity: Severity::Critical,
                regex: r"\b(sk-proj-[a-zA-Z0-9_-]{48,160})\b",
                keywords: &["sk-proj-"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "ai/openai-service-account-key",
                group: Group::Ai,
                name: "OpenAI Service Account Key",
                description: "Grants programmatic access to OpenAI services via a service account.",
                severity: Severity::Critical,
                regex: r"\b(sk-svcacct-[a-zA-Z0-9_-]{48,160})\b",
                keywords: &["sk-svcacct-"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "ai/openai-none-key",
                group: Group::Ai,
                name: "OpenAI None-Scoped Key",
                description: "Grants access to OpenAI services via an unscoped API key.",
                severity: Severity::Critical,
                regex: r"\b(sk-None-[a-zA-Z0-9_-]{48,160})\b",
                keywords: &["sk-None-"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
    ],
);
