//! Slack secret patterns.

crate::declare_provider!(
    SlackProvider,
    id: "slack",
    name: "Slack",
    group: Group::Messaging,
    patterns: [
        crate::pattern! {
                id: "messaging/slack-app-token",
                group: Group::Messaging,
                name: "Slack App-Level Token",
                description: "Grants access to Socket Mode and app-level management APIs.",
                severity: Severity::High,
                regex: r"\b(xoxa-[0-9]+-[a-zA-Z0-9-]+)\b",
                keywords: &["xoxa-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "messaging/slack-bot-token",
                group: Group::Messaging,
                name: "Slack Bot Token",
                description: "Grants message posting and workspace interaction capabilities.",
                severity: Severity::Critical,
                regex: r"\b(xoxb-[0-9]{10,13}-[0-9]{10,13}-[a-zA-Z0-9]{24})\b",
                keywords: &["xoxb-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "messaging/slack-config-token",
                group: Group::Messaging,
                name: "Slack Configuration Token",
                description: "Grants access to app manifest and configuration APIs.",
                severity: Severity::High,
                regex: r"\b(xoxe\.xoxp-[0-9]+-[a-zA-Z0-9-]+)\b",
                keywords: &["xoxe."],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "messaging/slack-legacy-token",
                group: Group::Messaging,
                name: "Slack Legacy Token",
                description: "Grants broad workspace access (deprecated but functional).",
                severity: Severity::Critical,
                regex: r"\b(xoxs-[0-9]+-[a-zA-Z0-9-]+)\b",
                keywords: &["xoxs-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "messaging/slack-refresh-token",
                group: Group::Messaging,
                name: "Slack Refresh Token",
                description: "Grants ability to obtain new access tokens.",
                severity: Severity::Critical,
                regex: r"\b(xoxr-[0-9]+-[a-zA-Z0-9-]+)\b",
                keywords: &["xoxr-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "messaging/slack-user-token",
                group: Group::Messaging,
                name: "Slack User Token",
                description: "Grants user-level access including private channels and DMs.",
                severity: Severity::Critical,
                regex: r"\b(xoxp-[0-9]{10,13}-[0-9]{10,13}-[0-9]{10,13}-[a-f0-9]{32})\b",
                keywords: &["xoxp-"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "messaging/slack-webhook",
                group: Group::Messaging,
                name: "Slack Incoming Webhook URL",
                description: "Grants ability to post messages to a specific channel.",
                severity: Severity::Medium,
                regex: r"(https://hooks\.slack\.com/services/T[A-Z0-9]{8,12}/B[A-Z0-9]{8,12}/[a-zA-Z0-9]{24})",
                keywords: &["hooks.slack.com"],
                default_enabled: true,
                min_entropy: Some(2.5),
            },
    ],
);
