//! Shopify payment and commerce secret patterns.

crate::declare_provider!(
    ShopifyProvider,
    id: "shopify",
    name: "Shopify",
    group: Group::Payments,
    patterns: [
        crate::pattern! {
                id: "payments/shopify-access-token",
                group: Group::Payments,
                name: "Shopify Access Token",
                description: "Grants API access to store data and configuration.",
                severity: Severity::Critical,
                regex: r"\b(shpat_[a-fA-F0-9]{32,64})\b",
                keywords: &["shpat_"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "payments/shopify-custom-app-token",
                group: Group::Payments,
                name: "Shopify Custom App Access Token",
                description: "Grants full API access to the specific store.",
                severity: Severity::Critical,
                regex: r"\b(shpca_[a-fA-F0-9]{32,64})\b",
                keywords: &["shpca_"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "payments/shopify-private-app-token",
                group: Group::Payments,
                name: "Shopify Private App Access Token",
                description: "Grants full store API access (deprecated but functional).",
                severity: Severity::Critical,
                regex: r"\b(shppa_[a-fA-F0-9]{32,64})\b",
                keywords: &["shppa_"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "payments/shopify-shared-secret",
                group: Group::Payments,
                name: "Shopify App Shared Secret",
                description: "Allows webhook verification and OAuth authentication.",
                severity: Severity::High,
                regex: r"\b(shpss_[a-fA-F0-9]{32,64})\b",
                keywords: &["shpss_"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
    ],
);
