//! Doppler secret patterns.

crate::declare_provider!(
    DopplerProvider,
    id: "doppler",
    name: "Doppler",
    group: Group::Infra,
    patterns: [
        crate::pattern! {
                id: "infra/doppler-service-token",
                group: Group::Infra,
                name: "Doppler Service Token",
                description: "Grants access to secrets in a specific Doppler config.",
                severity: Severity::Critical,
                regex: r"\b(dp\.st\.[a-z0-9_-]{2,35}\.[a-zA-Z0-9]{40,44})\b",
                keywords: &["dp.st."],
                default_enabled: true,
                min_entropy: Some(3.5),
            },
            crate::pattern! {
                id: "infra/doppler-cli-token",
                group: Group::Infra,
                name: "Doppler CLI Token",
                description: "Grants CLI access to Doppler secrets.",
                severity: Severity::Critical,
                regex: r"\b(dp\.ct\.[a-zA-Z0-9]{40,44})\b",
                keywords: &["dp.ct."],
                default_enabled: true,
                min_entropy: Some(3.5),
            },
            crate::pattern! {
                id: "infra/doppler-personal-token",
                group: Group::Infra,
                name: "Doppler Personal Token",
                description: "Grants personal access to Doppler resources.",
                severity: Severity::Critical,
                regex: r"\b(dp\.pt\.[a-zA-Z0-9]{40,44})\b",
                keywords: &["dp.pt."],
                default_enabled: true,
                min_entropy: Some(3.5),
            },
            crate::pattern! {
                id: "infra/doppler-service-account-token",
                group: Group::Infra,
                name: "Doppler Service Account Token",
                description: "Grants service account access to Doppler.",
                severity: Severity::Critical,
                regex: r"\b(dp\.sa\.[a-zA-Z0-9]{40,44})\b",
                keywords: &["dp.sa."],
                default_enabled: true,
                min_entropy: Some(3.5),
            },
    ],
);
