//! Microsoft Azure secret patterns.

crate::declare_provider!(
    AzureProvider,
    id: "azure",
    name: "Microsoft Azure",
    group: Group::Cloud,
    patterns: [
        crate::pattern! {
                id: "cloud/azure-app-insights-instrumentation-key",
                group: Group::Cloud,
                name: "Azure Application Insights Instrumentation Key",
                description: "Could allow telemetry injection or data spoofing.",
                severity: Severity::Low,
                regex: r"InstrumentationKey=([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})",
                keywords: &["InstrumentationKey"],
                default_enabled: true,
                min_entropy: Some(3.0),
            },
            crate::pattern! {
                id: "cloud/azure-service-bus-key",
                group: Group::Cloud,
                name: "Azure Service Bus Shared Access Key",
                description: "Grants send/receive access to messaging namespace.",
                severity: Severity::Critical,
                regex: r"SharedAccessKey=([A-Za-z0-9+/]{43}=)",
                keywords: &["SharedAccessKey"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "cloud/azure-storage-account-key",
                group: Group::Cloud,
                name: "Azure Storage Account Key",
                description: "Grants full read/write/delete access to storage account.",
                severity: Severity::Critical,
                regex: r"AccountKey=([A-Za-z0-9+/]{86}==)",
                keywords: &["AccountKey"],
                default_enabled: true,
                min_entropy: Some(4.5),
            },
            crate::pattern! {
                id: "cloud/azure-storage-sas-token",
                group: Group::Cloud,
                name: "Azure Storage SAS Token",
                description: "Grants delegated storage access based on token permissions.",
                severity: Severity::High,
                regex: r"https?://[a-zA-Z0-9.-]+\.(?:blob|queue|table|file)\.core\.windows\.net[^\s]*[?&]sig=([A-Za-z0-9%+/]+={0,2})",
                keywords: &["blob.core.windows.net", "queue.core.windows.net", "table.core.windows.net", "file.core.windows.net"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
    ],
);
