//! Private key and certificate patterns.

crate::declare_provider!(
    KeysProvider,
    id: "keys",
    name: "Private Keys & Certificates",
    group: Group::Keys,
    patterns: [
        crate::pattern! {
                id: "keys/rsa-private-key",
                group: Group::Keys,
                name: "RSA Private Key",
                description: "Grants decryption, signing, and server impersonation capabilities.",
                severity: Severity::Critical,
                regex: r"-----BEGIN RSA PRIVATE KEY-----[\s\S]{64,}?-----END RSA PRIVATE KEY-----",
                keywords: &["BEGIN RSA PRIVATE KEY"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "keys/private-key-pkcs8",
                group: Group::Keys,
                name: "PKCS#8 Private Key",
                description: "Grants cryptographic capabilities depending on contained key type.",
                severity: Severity::Critical,
                regex: r"-----BEGIN PRIVATE KEY-----[\s\S]{64,}?-----END PRIVATE KEY-----",
                keywords: &["BEGIN PRIVATE KEY"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "keys/ec-private-key",
                group: Group::Keys,
                name: "EC Private Key",
                description: "Grants TLS/SSH authentication and digital signing capabilities.",
                severity: Severity::Critical,
                regex: r"-----BEGIN EC PRIVATE KEY-----[\s\S]{64,}?-----END EC PRIVATE KEY-----",
                keywords: &["BEGIN EC PRIVATE KEY"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "keys/dsa-private-key",
                group: Group::Keys,
                name: "DSA Private Key",
                description: "Grants digital signing capabilities (legacy algorithm).",
                severity: Severity::Critical,
                regex: r"-----BEGIN DSA PRIVATE KEY-----[\s\S]{64,}?-----END DSA PRIVATE KEY-----",
                keywords: &["BEGIN DSA PRIVATE KEY"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "keys/openssh-private-key",
                group: Group::Keys,
                name: "OpenSSH Private Key",
                description: "Grants SSH access to configured remote servers.",
                severity: Severity::Critical,
                regex: r"-----BEGIN OPENSSH PRIVATE KEY-----[\s\S]{64,}?-----END OPENSSH PRIVATE KEY-----",
                keywords: &["BEGIN OPENSSH PRIVATE KEY"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "keys/encrypted-private-key",
                group: Group::Keys,
                name: "Encrypted Private Key",
                description: "Grants cryptographic access if password is weak or compromised.",
                severity: Severity::High,
                regex: r"-----BEGIN ENCRYPTED PRIVATE KEY-----[\s\S]{64,}?-----END ENCRYPTED PRIVATE KEY-----",
                keywords: &["BEGIN ENCRYPTED PRIVATE KEY"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "keys/pgp-private-key",
                group: Group::Keys,
                name: "PGP Private Key Block",
                description: "Grants email decryption and identity signing capabilities.",
                severity: Severity::Critical,
                regex: r"-----BEGIN PGP PRIVATE KEY BLOCK-----[\s\S]{64,}?-----END PGP PRIVATE KEY BLOCK-----",
                keywords: &["BEGIN PGP PRIVATE KEY BLOCK"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "keys/putty-private-key",
                group: Group::Keys,
                name: "PuTTY Private Key",
                description: "Grants SSH access to configured remote servers.",
                severity: Severity::Critical,
                regex: r"PuTTY-User-Key-File-[0-9]+:[\s\S]{40,}?Private-Lines:",
                keywords: &["PuTTY-User-Key-File"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
            crate::pattern! {
                id: "keys/pkcs12-certificate",
                group: Group::Keys,
                name: "PKCS#12 Certificate (PFX/P12)",
                description: "Grants TLS client authentication and server identity impersonation.",
                severity: Severity::Critical,
                regex: r#"(?i)(?:pfx|p12|pkcs12)[_\-]?(?:data|cert|key|content|base64|encoded)?\s*[=:]\s*["']?(MII[A-Za-z0-9+/]{100,}={0,2})["']?"#,
                keywords: &["pfx", "p12", "pkcs12"],
                default_enabled: true,
                min_entropy: Some(4.5),
            },
            crate::pattern! {
                id: "keys/age-secret-key",
                group: Group::Keys,
                name: "Age Encryption Secret Key",
                description: "Grants decryption of age-encrypted files and data.",
                severity: Severity::Critical,
                regex: r"\b(AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58})\b",
                keywords: &["AGE-SECRET-KEY-1"],
                default_enabled: true,
                min_entropy: Some(4.0),
            },
    ],
);
